<?php


namespace SchemaOrg;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * Service
 * 
 * @link http://schema.org/Service
 * 
 * @ORM\MappedSuperclass
 */
class Service extends Intangible
{
    /**
     * Available Channel
     * 
     * @var ServiceChannel $availableChannel A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)
     * 
     * @ORM\ManyToOne(targetEntity="ServiceChannel")
     */
    private $availableChannel;
    /**
     * Produces
     * 
     * @var Thing $produces The tangible thing generated by the service, e.g. a passport, permit, etc.
     * 
     * @ORM\ManyToOne(targetEntity="Thing")
     * @ORM\JoinColumn(nullable=false)
     */
    private $produces;
    /**
     * Provider
     * 
     * @var Organization $provider The organization or agency that is providing the service.
     * 
     * @ORM\ManyToOne(targetEntity="Organization")
     * @ORM\JoinColumn(nullable=false)
     */
    private $provider;
    /**
     * Service Area
     * 
     * @var AdministrativeArea $serviceArea The geographic area where the service is provided.
     * 
     * @ORM\ManyToOne(targetEntity="AdministrativeArea")
     * @ORM\JoinColumn(nullable=false)
     */
    private $serviceArea;
    /**
     * Service Audience
     * 
     * @var Audience $serviceAudience The audience eligible for this service.
     * 
     * @ORM\ManyToOne(targetEntity="Audience")
     * @ORM\JoinColumn(nullable=false)
     */
    private $serviceAudience;
    /**
     * Service Type
     * 
     * @var string $serviceType The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     * 
     * @Assert\Type(type="string")
     * @ORM\Column
     */
    private $serviceType;
}
