<?php

namespace SchemaOrg;

/**
 * Service
 *
 * @link http://schema.org/Service
 */
class Service extends Intangible
{
    /**
     * Available Channel
     *
     * @var ServiceChannel A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)
     */
    protected $availableChannel;
    /**
     * Produces
     *
     * @var Thing The tangible thing generated by the service, e.g. a passport, permit, etc.
     */
    protected $produces;
    /**
     * Provider (Organization)
     *
     * @var Organization The organization or agency that is providing the service.
     */
    protected $providerOrganization;
    /**
     * Provider (Person)
     *
     * @var Person The organization or agency that is providing the service.
     */
    protected $providerPerson;
    /**
     * Service Area
     *
     * @var AdministrativeArea The geographic area where the service is provided.
     */
    protected $serviceArea;
    /**
     * Service Audience
     *
     * @var Audience The audience eligible for this service.
     */
    protected $serviceAudience;
    /**
     * Service Type
     *
     * @var string The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     */
    protected $serviceType;
}
